# Generated by Django 5.0.6 on 2024-08-31 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_categories_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='categories.categories')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
    ]
