# Generated by Django 5.0.6 on 2025-03-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subCategories', '0002_rename_slug_subcategories_slug_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
