# Generated by Django 5.0.6 on 2024-09-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categories_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='slug',
            new_name='slug_cate',
        ),
    ]
