# Generated by Django 5.0.6 on 2024-07-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesslider',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imagesslider',
            name='date_upload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
