# Generated by Django 5.0.6 on 2024-09-08 03:10

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subCategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('brand', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=200)),
                ('image', models.ImageField(default='./default/placeholder.webp', max_length=5000, upload_to=products.models.Products.image_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='subCategories.subcategories')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
