# Generated by Django 5.0.6 on 2024-09-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='slug',
            new_name='slug_prod',
        ),
    ]
