# Generated by Django 5.0.6 on 2024-10-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_slug_products_slug_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(default='', max_length=20),
        ),
    ]
