# Generated by Django 5.0.6 on 2024-10-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes')], default='', max_length=20),
        ),
    ]
