# Generated by Django 5.0.6 on 2024-10-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='size',
            new_name='size_clothing',
        ),
        migrations.AddField(
            model_name='products',
            name='size_shoes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
