# Generated by Django 5.0.6 on 2024-10-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_size_products_size_clothing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='products',
            name='size_clothing',
        ),
        migrations.RemoveField(
            model_name='products',
            name='size_shoes',
        ),
    ]
